/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadoragui.vista;

import calculadoragui.control.GestioCalculadoraGuiAvanzada;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author dblan
 */
public class InterficieGraficaAvanzada extends javax.swing.JFrame {

    private GestioCalculadoraGuiAvanzada gCalAv;
    
    /**
     * Creates new form interficieGraficaAvanzada
     */
    public InterficieGraficaAvanzada() {
        gCalAv = new GestioCalculadoraGuiAvanzada(this);
        initComponents();
        this.setLocationRelativeTo(null);// centra el formulari en la pantalla
        inicia();
    }
/**
 * Es configuren els objectes dels butons perquè la classe que farà de Listener
 * de l'esdeveniment click (tipus ActionEvent) serà GestioCalculadoraGui
 */
    private void inicia() {
        jButtonSuma.addActionListener(gCalAv);
        jButtonDivisio.addActionListener(gCalAv);
        jButtonResta.addActionListener(gCalAv);
        jButtonMultiplicacio.addActionListener(gCalAv);
        jButtonPotencia.addActionListener(gCalAv);
        jButtonMaxim.addActionListener(gCalAv);
        jButtonMinim.addActionListener(gCalAv);
        jButtonPotencia.addActionListener(gCalAv);

    }
    
    
    
    
    
    /**
     * Mostra un quadre de diàleg amb el missatge d'error que li arriba per
     * paràmetre.
     *
     * @param missatge
     */
    public void mostrarMissatgeError(String missatge) {
        JOptionPane.showMessageDialog(rootPane, missatge, "Error", JOptionPane.ERROR_MESSAGE);
    }

    public double getOper1() {
        return Double.parseDouble(this.jTextFieldOper1.getText());
    }

    public double getOper2() {
        return Double.parseDouble(this.jTextFieldOper2.getText());
    }

    public void setResultat(double result) {
        DecimalFormat formatter = new DecimalFormat("#0.00");
        this.jTextFieldResultat.setText(formatter.format(result));
    }

    public void buidarTextFields() {
        this.jTextFieldOper1.setText("");
        this.jTextFieldOper2.setText("");
        this.jTextFieldResultat.setText("");
    }
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    private void jButtonNetejarActionPerformed(java.awt.event.ActionEvent evt) {                                               
        buidarTextFields();
    }                                              

    private void jButtonSortirActionPerformed(java.awt.event.ActionEvent evt) {                                              
        System.exit(0);
    }                            
    
    // Variables declaration - do not modify                     
    private javax.swing.JButton jButtonDivisio;
    private javax.swing.JButton jButtonMultiplicacio;
    private javax.swing.JButton jButtonNetejar;
    private javax.swing.JButton jButtonResta;
    private javax.swing.JButton jButtonSortir;
    private javax.swing.JButton jButtonSuma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldOper1;
    private javax.swing.JTextField jTextFieldOper2;
    private javax.swing.JTextField jTextFieldResultat;
    // End of variables declaration                   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
